// <auto-generated />
using System;
using Backend.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427180218_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Felhasznalo.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("Engedelyek")
                        .HasColumnType("tinyint");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("Backend.Models.Macska.Macska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ar")
                        .HasColumnType("int");

                    b.Property<byte>("Kor")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Szin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Macskak");
                });

            modelBuilder.Entity("Backend.Models.Rendeles.Rendeles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Felhasznalo")
                        .HasColumnType("int");

                    b.Property<DateTime>("RendelesIdeje")
                        .HasColumnType("datetime2");

                    b.Property<string>("SzallitasiCim")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Felhasznalo");

                    b.ToTable("Rendelesek");
                });

            modelBuilder.Entity("Backend.Models.Rendeles.RendeleshezTartozik", b =>
                {
                    b.Property<int>("Rendeles")
                        .HasColumnType("int");

                    b.Property<int>("Macska")
                        .HasColumnType("int");

                    b.Property<int>("Mennyiseg")
                        .HasColumnType("int");

                    b.HasKey("Rendeles", "Macska");

                    b.HasIndex("Macska");

                    b.ToTable("RendeleshezTartozikok");
                });

            modelBuilder.Entity("Backend.Models.Rendeles.Rendeles", b =>
                {
                    b.HasOne("Backend.Models.Felhasznalo.Felhasznalo", "_Felhasznalo")
                        .WithMany("_Rendelesek")
                        .HasForeignKey("Felhasznalo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Felhasznalo");
                });

            modelBuilder.Entity("Backend.Models.Rendeles.RendeleshezTartozik", b =>
                {
                    b.HasOne("Backend.Models.Macska.Macska", "_Macska")
                        .WithMany("_RendeleshezTartozikok")
                        .HasForeignKey("Macska")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Rendeles.Rendeles", "_Rendeles")
                        .WithMany("_RendeleshezTartozikok")
                        .HasForeignKey("Rendeles")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Macska");

                    b.Navigation("_Rendeles");
                });

            modelBuilder.Entity("Backend.Models.Felhasznalo.Felhasznalo", b =>
                {
                    b.Navigation("_Rendelesek");
                });

            modelBuilder.Entity("Backend.Models.Macska.Macska", b =>
                {
                    b.Navigation("_RendeleshezTartozikok");
                });

            modelBuilder.Entity("Backend.Models.Rendeles.Rendeles", b =>
                {
                    b.Navigation("_RendeleshezTartozikok");
                });
#pragma warning restore 612, 618
        }
    }
}
